/* tslint:disable */
/* eslint-disable */
/*
Discourse API Documentation

This page contains the documentation on how to use Discourse through API calls.

> Note: For any endpoints not listed you can follow the
[reverse engineer the Discourse API](https://meta.discourse.org/t/-/20576)
guide to figure out how to use an API endpoint.

### Request Content-Type

The Content-Type for POST and PUT requests can be set to `application/x-www-form-urlencoded`,
`multipart/form-data`, or `application/json`.

### Endpoint Names and Response Content-Type

Most API endpoints provide the same content as their HTML counterparts. For example
the URL `/categories` serves a list of categories, the `/categories.json` API provides the
same information in JSON format.

Instead of sending API requests to `/categories.json` you may also send them to `/categories`
and add an `Accept: application/json` header to the request to get the JSON response.
Sending requests with the `Accept` header is necessary if you want to use URLs
for related endpoints returned by the API, such as pagination URLs.
These URLs are returned without the `.json` prefix so you need to add the header in
order to get the correct response format.

### Authentication

Some endpoints do not require any authentication, pretty much anything else will
require you to be authenticated.

To become authenticated you will need to create an API Key from the admin panel.

Once you have your API Key you can pass it in along with your API Username
as an HTTP header like this:

```
curl -X GET \"http://127.0.0.1:3000/admin/users/list/active.json\" \\
-H \"Api-Key: 714552c6148e1617aeab526d0606184b94a80ec048fc09894ff1a72b740c5f19\" \\
-H \"Api-Username: system\"
```

and this is how POST requests will look:

```
curl -X POST \"http://127.0.0.1:3000/categories\" \\
-H \"Content-Type: multipart/form-data;\" \\
-H \"Api-Key: 714552c6148e1617aeab526d0606184b94a80ec048fc09894ff1a72b740c5f19\" \\
-H \"Api-Username: system\" \\
-F \"name=89853c20-4409-e91a-a8ea-f6cdff96aaaa\" \\
-F \"color=49d9e9\" \\
-F \"text_color=f0fcfd\"
```

### Boolean values

If an endpoint accepts a boolean be sure to specify it as a lowercase
`true` or `false` value unless noted otherwise.


The version of the OpenAPI document: latest


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CategoriesCreateCategoryRequestRequest } from '../models';
// @ts-ignore
import { CategoriesCreateCategoryRequestRequestPermissions } from '../models';
// @ts-ignore
import { CategoriesCreateCategoryRequestResponse } from '../models';
// @ts-ignore
import { CategoriesGetCategoryByIdJsonResponse } from '../models';
// @ts-ignore
import { CategoriesListResponse } from '../models';
// @ts-ignore
import { CategoriesListTopicsResponse } from '../models';
// @ts-ignore
import { CategoriesUpdateCategoryByIdJsonRequest } from '../models';
// @ts-ignore
import { CategoriesUpdateCategoryByIdJsonRequestPermissions } from '../models';
// @ts-ignore
import { CategoriesUpdateCategoryByIdJsonResponse } from '../models';
// @ts-ignore
import { SiteGetCategoriesAndSubcategoriesResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a category
         * @param {CategoriesCreateCategoryRequestRequest} [categoriesCreateCategoryRequestRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCategoryRequest: async (categoriesCreateCategoryRequestRequest?: CategoriesCreateCategoryRequestRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: categoriesCreateCategoryRequestRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/categories.json',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(categoriesCreateCategoryRequestRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Can be used to fetch all categories and subcategories
         * @summary Get site info
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoriesAndSubcategories: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/site.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/site.json',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Show category
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryByIdJson: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCategoryByIdJson', 'id', id)
            const localVarPath = `/c/{id}/show.json`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/c/{id}/show.json',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a list of categories
         * @param {boolean} [includeSubcategories] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (includeSubcategories?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            if (includeSubcategories !== undefined) {
                localVarQueryParameter['include_subcategories'] = includeSubcategories;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/categories.json',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List topics
         * @param {string} slug 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTopics: async (slug: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('listTopics', 'slug', slug)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listTopics', 'id', id)
            const localVarPath = `/c/{slug}/{id}.json`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug !== undefined ? slug : `-slug-`)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/c/{slug}/{id}.json',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a category
         * @param {number} id 
         * @param {CategoriesUpdateCategoryByIdJsonRequest} [categoriesUpdateCategoryByIdJsonRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategoryByIdJson: async (id: number, categoriesUpdateCategoryByIdJsonRequest?: CategoriesUpdateCategoryByIdJsonRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCategoryByIdJson', 'id', id)
            const localVarPath = `/categories/{id}.json`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: categoriesUpdateCategoryByIdJsonRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/categories/{id}.json',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(categoriesUpdateCategoryByIdJsonRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoriesApi - functional programming interface
 * @export
 */
export const CategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a category
         * @param {CategoriesApiCreateCategoryRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCategoryRequest(requestParameters: CategoriesApiCreateCategoryRequestRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoriesCreateCategoryRequestResponse>> {
            const categoriesCreateCategoryRequestRequest: CategoriesCreateCategoryRequestRequest = {
                name: requestParameters.name,
                color: requestParameters.color,
                text_color: requestParameters.text_color,
                parent_category_id: requestParameters.parent_category_id,
                allow_badges: requestParameters.allow_badges,
                slug: requestParameters.slug,
                topic_featured_links_allowed: requestParameters.topic_featured_links_allowed,
                permissions: requestParameters.permissions,
                search_priority: requestParameters.search_priority,
                form_template_ids: requestParameters.form_template_ids
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCategoryRequest(categoriesCreateCategoryRequestRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Can be used to fetch all categories and subcategories
         * @summary Get site info
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategoriesAndSubcategories(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SiteGetCategoriesAndSubcategoriesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategoriesAndSubcategories(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Show category
         * @param {CategoriesApiGetCategoryByIdJsonRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategoryByIdJson(requestParameters: CategoriesApiGetCategoryByIdJsonRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoriesGetCategoryByIdJsonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategoryByIdJson(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Retrieves a list of categories
         * @param {CategoriesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: CategoriesApiListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoriesListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.includeSubcategories, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List topics
         * @param {CategoriesApiListTopicsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTopics(requestParameters: CategoriesApiListTopicsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoriesListTopicsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTopics(requestParameters.slug, requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Updates a category
         * @param {CategoriesApiUpdateCategoryByIdJsonRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCategoryByIdJson(requestParameters: CategoriesApiUpdateCategoryByIdJsonRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoriesUpdateCategoryByIdJsonResponse>> {
            const categoriesUpdateCategoryByIdJsonRequest: CategoriesUpdateCategoryByIdJsonRequest = {
                name: requestParameters.name,
                color: requestParameters.color,
                text_color: requestParameters.text_color,
                parent_category_id: requestParameters.parent_category_id,
                allow_badges: requestParameters.allow_badges,
                slug: requestParameters.slug,
                topic_featured_links_allowed: requestParameters.topic_featured_links_allowed,
                permissions: requestParameters.permissions,
                search_priority: requestParameters.search_priority,
                form_template_ids: requestParameters.form_template_ids
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCategoryByIdJson(requestParameters.id, categoriesUpdateCategoryByIdJsonRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CategoriesApi - factory interface
 * @export
 */
export const CategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a category
         * @param {CategoriesApiCreateCategoryRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCategoryRequest(requestParameters: CategoriesApiCreateCategoryRequestRequest, options?: AxiosRequestConfig): AxiosPromise<CategoriesCreateCategoryRequestResponse> {
            return localVarFp.createCategoryRequest(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Can be used to fetch all categories and subcategories
         * @summary Get site info
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoriesAndSubcategories(options?: AxiosRequestConfig): AxiosPromise<SiteGetCategoriesAndSubcategoriesResponse> {
            return localVarFp.getCategoriesAndSubcategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Show category
         * @param {CategoriesApiGetCategoryByIdJsonRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryByIdJson(requestParameters: CategoriesApiGetCategoryByIdJsonRequest, options?: AxiosRequestConfig): AxiosPromise<CategoriesGetCategoryByIdJsonResponse> {
            return localVarFp.getCategoryByIdJson(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a list of categories
         * @param {CategoriesApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: CategoriesApiListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<CategoriesListResponse> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List topics
         * @param {CategoriesApiListTopicsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTopics(requestParameters: CategoriesApiListTopicsRequest, options?: AxiosRequestConfig): AxiosPromise<CategoriesListTopicsResponse> {
            return localVarFp.listTopics(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a category
         * @param {CategoriesApiUpdateCategoryByIdJsonRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCategoryByIdJson(requestParameters: CategoriesApiUpdateCategoryByIdJsonRequest, options?: AxiosRequestConfig): AxiosPromise<CategoriesUpdateCategoryByIdJsonResponse> {
            return localVarFp.updateCategoryByIdJson(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createCategoryRequest operation in CategoriesApi.
 * @export
 * @interface CategoriesApiCreateCategoryRequestRequest
 */
export type CategoriesApiCreateCategoryRequestRequest = {
    
} & CategoriesCreateCategoryRequestRequest

/**
 * Request parameters for getCategoryByIdJson operation in CategoriesApi.
 * @export
 * @interface CategoriesApiGetCategoryByIdJsonRequest
 */
export type CategoriesApiGetCategoryByIdJsonRequest = {
    
    /**
    * 
    * @type {number}
    * @memberof CategoriesApiGetCategoryByIdJson
    */
    readonly id: number
    
}

/**
 * Request parameters for list operation in CategoriesApi.
 * @export
 * @interface CategoriesApiListRequest
 */
export type CategoriesApiListRequest = {
    
    /**
    * 
    * @type {boolean}
    * @memberof CategoriesApiList
    */
    readonly includeSubcategories?: boolean
    
}

/**
 * Request parameters for listTopics operation in CategoriesApi.
 * @export
 * @interface CategoriesApiListTopicsRequest
 */
export type CategoriesApiListTopicsRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof CategoriesApiListTopics
    */
    readonly slug: string
    
    /**
    * 
    * @type {number}
    * @memberof CategoriesApiListTopics
    */
    readonly id: number
    
}

/**
 * Request parameters for updateCategoryByIdJson operation in CategoriesApi.
 * @export
 * @interface CategoriesApiUpdateCategoryByIdJsonRequest
 */
export type CategoriesApiUpdateCategoryByIdJsonRequest = {
    
    /**
    * 
    * @type {number}
    * @memberof CategoriesApiUpdateCategoryByIdJson
    */
    readonly id: number
    
} & CategoriesUpdateCategoryByIdJsonRequest

/**
 * CategoriesApiGenerated - object-oriented interface
 * @export
 * @class CategoriesApiGenerated
 * @extends {BaseAPI}
 */
export class CategoriesApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Creates a category
     * @param {CategoriesApiCreateCategoryRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiGenerated
     */
    public createCategoryRequest(requestParameters: CategoriesApiCreateCategoryRequestRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).createCategoryRequest(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Can be used to fetch all categories and subcategories
     * @summary Get site info
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiGenerated
     */
    public getCategoriesAndSubcategories(options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategoriesAndSubcategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Show category
     * @param {CategoriesApiGetCategoryByIdJsonRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiGenerated
     */
    public getCategoryByIdJson(requestParameters: CategoriesApiGetCategoryByIdJsonRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategoryByIdJson(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieves a list of categories
     * @param {CategoriesApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiGenerated
     */
    public list(requestParameters: CategoriesApiListRequest = {}, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List topics
     * @param {CategoriesApiListTopicsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiGenerated
     */
    public listTopics(requestParameters: CategoriesApiListTopicsRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).listTopics(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a category
     * @param {CategoriesApiUpdateCategoryByIdJsonRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiGenerated
     */
    public updateCategoryByIdJson(requestParameters: CategoriesApiUpdateCategoryByIdJsonRequest, options?: AxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).updateCategoryByIdJson(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
