/*
Discourse API Documentation

This page contains the documentation on how to use Discourse through API calls.

> Note: For any endpoints not listed you can follow the
[reverse engineer the Discourse API](https://meta.discourse.org/t/-/20576)
guide to figure out how to use an API endpoint.

### Request Content-Type

The Content-Type for POST and PUT requests can be set to `application/x-www-form-urlencoded`,
`multipart/form-data`, or `application/json`.

### Endpoint Names and Response Content-Type

Most API endpoints provide the same content as their HTML counterparts. For example
the URL `/categories` serves a list of categories, the `/categories.json` API provides the
same information in JSON format.

Instead of sending API requests to `/categories.json` you may also send them to `/categories`
and add an `Accept: application/json` header to the request to get the JSON response.
Sending requests with the `Accept` header is necessary if you want to use URLs
for related endpoints returned by the API, such as pagination URLs.
These URLs are returned without the `.json` prefix so you need to add the header in
order to get the correct response format.

### Authentication

Some endpoints do not require any authentication, pretty much anything else will
require you to be authenticated.

To become authenticated you will need to create an API Key from the admin panel.

Once you have your API Key you can pass it in along with your API Username
as an HTTP header like this:

```
curl -X GET \"http://127.0.0.1:3000/admin/users/list/active.json\" \\
-H \"Api-Key: 714552c6148e1617aeab526d0606184b94a80ec048fc09894ff1a72b740c5f19\" \\
-H \"Api-Username: system\"
```

and this is how POST requests will look:

```
curl -X POST \"http://127.0.0.1:3000/categories\" \\
-H \"Content-Type: multipart/form-data;\" \\
-H \"Api-Key: 714552c6148e1617aeab526d0606184b94a80ec048fc09894ff1a72b740c5f19\" \\
-H \"Api-Username: system\" \\
-F \"name=89853c20-4409-e91a-a8ea-f6cdff96aaaa\" \\
-F \"color=49d9e9\" \\
-F \"text_color=f0fcfd\"
```

### Boolean values

If an endpoint accepts a boolean be sure to specify it as a lowercase
`true` or `false` value unless noted otherwise.


The version of the OpenAPI document: latest


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TopicsGetSingleTopicResponseSuggestedTopicsInnerPostersInner } from './topics-get-single-topic-response-suggested-topics-inner-posters-inner';

/**
 * 
 * @export
 * @interface TopicsGetSingleTopicResponseSuggestedTopicsInner
 */
export interface TopicsGetSingleTopicResponseSuggestedTopicsInner {
    /**
     * 
     * @type {Array<any>}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'tags': Array<any>;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'fancy_title': string;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'slug': string;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'posts_count': number;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'reply_count': number;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'highest_post_number': number;
    /**
     * 
     * @type {any}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'image_url': any;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'created_at': string;
    /**
     * 
     * @type {any}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'last_posted_at': any;
    /**
     * 
     * @type {boolean}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'bumped': boolean;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'bumped_at': string;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'archetype': string;
    /**
     * 
     * @type {boolean}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'unseen': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'pinned': boolean;
    /**
     * 
     * @type {any}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'unpinned': any;
    /**
     * 
     * @type {string}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'excerpt': string;
    /**
     * 
     * @type {boolean}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'visible': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'closed': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'archived': boolean;
    /**
     * 
     * @type {any}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'bookmarked': any;
    /**
     * 
     * @type {any}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'liked': any;
    /**
     * 
     * @type {object}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'tags_descriptions': object;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'like_count': number;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'views': number;
    /**
     * 
     * @type {number}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'category_id': number;
    /**
     * 
     * @type {any}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'featured_link': any;
    /**
     * 
     * @type {Array<TopicsGetSingleTopicResponseSuggestedTopicsInnerPostersInner>}
     * @memberof TopicsGetSingleTopicResponseSuggestedTopicsInner
     */
    'posters': Array<TopicsGetSingleTopicResponseSuggestedTopicsInnerPostersInner>;
}

